# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\joinWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_joinWidget(object):
    def setupUi(self, loginWidget):
        loginWidget.setObjectName("loginWidget")
        loginWidget.resize(361, 520)
        self.gridLayout = QtWidgets.QGridLayout(loginWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pictureWidget = QtWidgets.QWidget(loginWidget)
        self.pictureWidget.setObjectName("pictureWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pictureWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editPushButton = QtWidgets.QPushButton(self.pictureWidget)
        self.editPushButton.setObjectName("editPushButton")
        self.gridLayout_2.addWidget(self.editPushButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(90, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(147, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.photoLabel = QtWidgets.QLabel(self.pictureWidget)
        self.photoLabel.setText("")
        self.photoLabel.setObjectName("photoLabel")
        self.gridLayout_2.addWidget(self.photoLabel, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.pictureWidget, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.loginLable = QtWidgets.QLabel(loginWidget)
        self.loginLable.setObjectName("loginLable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.loginLable)
        self.loginLineEdit = QtWidgets.QLineEdit(loginWidget)
        self.loginLineEdit.setClearButtonEnabled(True)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginLineEdit)
        self.passwordLable = QtWidgets.QLabel(loginWidget)
        self.passwordLable.setTextFormat(QtCore.Qt.AutoText)
        self.passwordLable.setObjectName("passwordLable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLable)
        self.passwordLineEdit = QtWidgets.QLineEdit(loginWidget)
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.emailLabel = QtWidgets.QLabel(loginWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtWidgets.QLineEdit(loginWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.imageLabel = QtWidgets.QLabel(loginWidget)
        self.imageLabel.setObjectName("imageLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.imageLabel)
        self.splitter = QtWidgets.QSplitter(loginWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.choosePhotoButton = QtWidgets.QToolButton(self.splitter)
        self.choosePhotoButton.setObjectName("choosePhotoButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.splitter)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okPushButton = QtWidgets.QPushButton(loginWidget)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(loginWidget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(loginWidget)
        QtCore.QMetaObject.connectSlotsByName(loginWidget)
        loginWidget.setTabOrder(self.loginLineEdit, self.passwordLineEdit)
        loginWidget.setTabOrder(self.passwordLineEdit, self.cancelPushButton)
        loginWidget.setTabOrder(self.cancelPushButton, self.okPushButton)

    def retranslateUi(self, loginWidget):
        _translate = QtCore.QCoreApplication.translate
        loginWidget.setWindowTitle(_translate("loginWidget", "Welcome"))
        self.editPushButton.setText(_translate("loginWidget", "edit"))
        self.loginLable.setText(_translate("loginWidget", "Login: "))
        self.passwordLable.setText(_translate("loginWidget", "Password: "))
        self.emailLabel.setText(_translate("loginWidget", "Email: "))
        self.imageLabel.setText(_translate("loginWidget", "Profile Photo:"))
        self.choosePhotoButton.setText(_translate("loginWidget", "Choose Photo"))
        self.okPushButton.setText(_translate("loginWidget", "Ok"))
        self.cancelPushButton.setText(_translate("loginWidget", "Cancel"))

